spring.application.name=demo

spring.datasource.url=jdbc:postgresql://localhost:5432/sundial
spring.datasource.username=sundial
spring.datasource.password=sundial
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

weather.api.key=
